ARG DOCKER_REGISTRY=docker.io
ARG FROM_IMG_REPO=qnib
ARG FROM_IMG_NAME=uplain-pip3
ARG FROM_IMG_TAG=2018-12-23.1
ARG FROM_IMG_HASH=""

FROM ${DOCKER_REGISTRY}/${FROM_IMG_REPO}/${FROM_IMG_NAME}:${FROM_IMG_TAG}${DOCKER_IMG_HASH}

ARG GDRIVE_ID=1GYEGX42g4wL-qKo0Yc434vgvfpHUx6Rl
RUN export CONFIRM=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate "https://docs.google.com/uc?export=download&id=${GDRIVE_ID}" -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p') \
 && wget -q --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$CONFIRM&id=${GDRIVE_ID}" -O tensorflow-1.11.0-cp36-cp36m-linux_x86_64.whl \
 && pip3 install tensorflow-1.11.0-cp36-cp36m-linux_x86_64.whl \
 && rm -f /tmp/cookies.txt \
 && rm -f tensorflow-1.11.0-cp36-cp36m-linux_x86_64.whl
RUN python -c 'import tensorflow as tf;hello = tf.constant("Hello, TensorFlow!");sess = tf.Session();print(sess.run(hello))'
RUN echo "python -c 'from tensorflow.python.client import device_lib;device_lib.list_local_devices()'" >> /root/.bash_history
